title: Caturnalia - Amici per gli scacchi
email: grisafi4@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Caturnalia è stata fondata da un gruppo di amici appassionati del gioco degli scacchi.
  Vogliamo avere un luogo dove si possa giocare a scacchi pensati o lampo, analizzare una partita o studiare, ma anche ridere e scherzare, 
  perchè gli scacchi sono forse un gioco difficile, ma restano comunque un gioco.
baseurl: "" 
url: "https://www.caturnalia.it" 
twitter_username: Sgri_dev
github_username:  Sgridev

# Build settings
theme: minima
plugins:
  - jekyll-feed

